/*

 TWON_M_001.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : C:\Users\dell\Documents\2 Proyectos personales\2 Programación\GB_Tile_designer\Archivos_editables\01\twon_001.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define town_001_mapWidth 32
#define town_001_mapHeight 18
#define town_001_mapBank 0

extern unsigned char town_001_map[];

/* End of TWON_M_001.H */
